[package]
name = "jarvis-modbus-exporter"
version = "0.1.0"
authors = ["Jorrit Salverda <jorrit.salverda@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
modbus = "1.0"
uuid = { version = "0.8", features = ["v4"] }
chrono = "0.4"
byteorder = "1"
conv = "0.3"