location: My Home
sampleConfigs:
- deviceName: Sunny TriPower 8.0
  sampleName: Totaal opgewekt
  aggregationLevel: 3
  metricType: 1
  sampleType: 1
  sampleUnit: 1
  valueMultiplier: 3600
  registerType: input
  registerAddress: 30513
  registerQuantity: 4