location: My Home
sampleConfigs:
- entityType: ENTITY_TYPE_DEVICE
  entityName: Sunny TriPower 8.0
  sampleType: SAMPLE_TYPE_ELECTRICITY_PRODUCTION
  sampleName: Totaal opgewekt
  metricType: METRIC_TYPE_COUNTER
  valueMultiplier: 3600
  registerType: input
  registerAddress: 30513
  registerQuantity: 4