version: 2.1
jobs:
  build:
    # working_directory: ~/repo
    docker:
      - image: cimg/rust:1.55
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-lock-{{ checksum "Cargo.lock" }}
      - run:
          name: Run tests
          command: cargo test
      - save_cache:
          key: cargo-lock-{{ checksum "Cargo.lock" }}
          paths:
            - "/app/target"
            - "/usr/local/cargo"
      # - run:
      #     name: Run tests
      #     command: |
      #       mkdir -p /tmp/test-reports
      #       gotestsum --junitfile /tmp/test-reports/unit-tests.xml
      # - store_test_results:
      #     path: /tmp/test-reports

workflows:
  build:
    jobs:
      - build
