# Default values for jarvis-modbus-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cronjob:
  schedule: '*/5 * * * *'
  concurrencyPolicy: Forbid

config:
  modbusHostIP: 127.0.0.1
  modbusHostPort: 502
  modbusUnitID: 3
  bqEnable: false
  bqProjectID: gcp-project-id
  bqDataset: jarvis
  bqTable: jarvis-measurements
  configYaml: |
    location: My Home
    sampleConfigs:
    - name: Sunny TriPower 8.0
      displayName: Totaal opgewekt
      aggregationLevel: AGGREGATION_LEVEL_DEVICE
      metricType: METRIC_TYPE_COUNTER
      sampleType: SampleType_SAMPLE_TYPE_ELECTRICITY
      sampleUnit: SAMPLE_UNIT_WATT_SECOND
      valueMultiplier: 3600
      registerType: input
      registerAddress: 30513
      registerQuantity: 4

secret:
  gcpServiceAccountKeyfile: '{}'

logFormat: json

image:
  repository: jsalverda/jarvis-modbus-exporter
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

rbac:
  # Specifies whether roles and bindings should be created
  enable: true

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  privileged: true
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
