apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jarvis-modbus-exporter.fullname" . }}
  labels:
    {{- include "jarvis-modbus-exporter.labels" . | nindent 4 }}
data:
  modbus-host-ip: {{ .Values.config.modbusHostIP | quote }}
  modbus-host-port: {{ .Values.config.modbusHostPort | quote }}
  modbus-unit-id: {{ .Values.config.modbusUnitID | quote }}
  nats-host:  {{ .Values.config.natsHost | quote }}
  nats-subject:  {{ .Values.config.natsSubject | quote }}
  config.yaml: |
    {{- with .Values.config.configYaml }}
    {{- tpl . $ | nindent 4 }}
    {{- end }}